- name: install
  apt: name={{ item }} state=present
  with_items:
    - make
    - git
    - python-dev
    - nginx
- name: install python softwares
  pip: name={{ item }} extra_args='--pre' state=present
  with_items:
    - tornado
    - supervisor
- include: supervisor.yml
- include: nginx.yml

- name: pull menes from github
  sudo: no
  git: repo=https://github.com/shirou/menes
       dest=/home/{{ user_name }}/menes
