---
- name: install python-selinux
  sudo: yes
  yum: pkg=libselinux-python state=latest
- name: install dependency
  sudo: yes
  apt: pkg={{ item }} state=installed
  with_items:
    - python
    - python-pip
    - python-dev
- name: install sphinx
  sudo: yes
  pip: name={{ item }}
  with_items:
    - tornado
    - celery
    - redis